### ISSUE TITLE
Unable to register in the application.

### ISSUE THREAD

**Issue by cbrahme** [airavata-courses/Architects#92]
I am trying to register a new user for the application.
Even after filling the registration form with given requirements I am getting an error saying 'Invalid Data'.

**Comment by harishmaruthi** [comment]
Looks like this was tested when the whole instance was not completely up. Another reviewer was building and testing. @bhushanmalgaonkar tested the functionality was working fine. Please do verify again by running the pipeline job on jenkins to rebuild the project completely and close the issue if the issue is not persistent.

Thanks for letting us know about this.

**Comment by cbrahme** [comment]
Yes. It's working fine.
